# laptop
wallpaper {
    monitor = eDP-1
    path = ~/photos/wallpapers/chill-lofi.png
    fit_mode = cover
}
wallpaper {
    monitor = DP-1
    path = ~/photos/wallpapers/chill-lofi.png
    fit_mode = cover
}

# pc
wallpaper {
    monitor = HDMI-A-1
    path = ~/photos/wallpapers/chill-lofi.png
    fit_mode = cover
}

splash = false
