general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = hyprlock
    after_sleep_cmd = hyprlock
}

# Lock after 5 minutes of no activity
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Suspend 5 more minutes later (5 min of no input on the lock screen)
listener {
    timeout = 600
    on-timeout = systemctl suspend
}
